---
name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-clj:
    strategy:
      matrix:
        # Supported Java versions: LTS releases and latest
        jdk: [8, 11, 17, 21]
        clojure: [11]

    name: Clojure ${{ matrix.clojure }} (Java ${{ matrix.jdk }})

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.jdk }}
          cache: maven
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - name: Run tests
        run: CLOJURE_ALIAS=clojure-${{ matrix.clojure }} bin/run-clojure-tests

  build-cljs:
    name: ClojureScript
    strategy:
      matrix:
        mode: [none, advanced, cherry-none, cherry-advanced]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
          cache: maven
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 16
      - name: Run tests on ${{ matrix.mode }}
        run: bin/run-cljs-tests ${{ matrix.mode }}
